### ISSUE TITLE
Docs: Add usage .md files for each component

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#619]
### Which Component

- [x] calcite-action-bar * #628 
- [x] calcite-action (@driskull) #620
- [x] ~~calcite-action-group~~ // not needed
- [x] calcite-action-pad * #635 
- [x] calcite-block* #637 
- [ ] calcite-block-section
- [x] ~~calcite-demo-nav~~ // not needed
- [x] ~~calcite-example~~ // not needed
- [x] ~~calcite-filter~~ //not needed for now
- [x] calcite-flow* #695 
- [ ] calcite-flow-item
- [x] calcite-panel* #697 
- [x] calcite-pick-list* #699 
- [ ] calcite-pick-list-group
- [ ] calcite-pick-list-item
- [x] calcite-shell* #701 
- [x] calcite-shell-panel* #702 
- [x] calcite-tip* #705 
- [x] ~~calcite-tip-group~~ // not necessary
- [x] calcite-tip-manager* #703 
- [x] calcite-value-list* #704 
- [ ] calcite-value-list-item

@kat10140 if this is too much work, we can divy up the components. Let us know.

We can also prioritize which components need usage docs first.

### Resources 

1. Create a `basic.md` file in a `usage` folder inside each components folder.
2. Add HTML snippets on how the component will be used.
3. Add more advanced `.md` files as necessary for each component.
4. The name of the file will be translated into a header in the documentation for that component, so we should come up with a standard file naming convention. We can have things like `basic`, `advanced` or more specific examples and use cases for each component usage.

Example: https://github.com/Esri/calcite-components/blob/master/src/components/calcite-tooltip/usage/basic.md

Marked as high priority to support users

**Comment by kat10140** [comment]
I put stars by the ones that I think are higher priority. I'll probably just go down the list.  Please feel free to modify the original comment errybody

**Comment by kat10140** [comment]
@driskull i see you marked as installed. Do you think it's fine to just have the main components that are highlighted by storybook to have usage folders and snippets?

**Comment by driskull** [comment]
Whoops my bad.

> Do you think it's fine to just have the main components that are highlighted by storybook to have usage folders and snippets?

Yeah I think so. We could always do the sub ones later if needed. Seems kinda redundant for the `calcite-action-group` and such.

**Comment by kat10140** [comment]
Sounds good!
